(define (problem jars1)
   (:domain jars)
   (:objects j4 j3 - jug)
   (:init (= (amount j4) 0)
          (= (amount j3) 0)
          (= (capacity j4) 4)
          (= (capacity j3) 3)
   )
   (:goal (and (= (amount j4) 2)
               (= (amount j3) 3)
          ))
)
