(define (problem listaexercicio6)
   (:domain blocksworld3s)
   (:objects a b c d e f g - block p1 p2 p3 - stack)
   (:init (on-table a) (on b a) (on c b) (clear c)
          (on-table d) (on e d) (clear e)
          (on-table f) (on g f) (clear g)
          (block-at a p1) (block-at b p1) (block-at c p1)
          (block-at d p2) (block-at e p2)
          (block-at f p3) (block-at g p3)
          (arm-empty))
   (:goal (and (block-at a p2) (on-table a) (on b a) (on c b) (on g c) (on f g) (clear f)
               (block-at e p3) (on-table e) (on d e) (clear d)
          ))
)
