(define (problem listaexercicio6)
   (:domain blocksworld3p)
   (:objects a b c d e f g p1 p2 p3)
   (:init (on-table a p1) (on b a p1) (on c b p1) (clear c p1)
          (on-table d p2) (on e d p2) (clear e p2)
          (on-table f p3) (on g f p3) (clear g p3)
          (arm-empty))
   (:goal (and (on-table a p2) (on b a p2) (on c b p2) (on g c p2) (on f g p2) (clear f p2)
               (on-table e p3) (on d e p3) (clear d p3)
          ))
)
